<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <title>Document</title>
</head>
<style>
    .tbl_schedule {
        width: 100%;
        border-collapse: collapse;
    }
    .tbl_schedule th {
        border: 1px solid black;
        color: red;
        font-size: 10px;
    }

    .tbl_schedule td {
        border: 1px solid black;
        font-size: 10px;
        text-align:center;
    }

    .header {
        text-align:center;
        font-size:20px;
        text-transform:uppercase;
        font-weight:bold;
    }

    .sub-header {
        text-align:center;
        font-size:13px;
        text-transform:uppercase;
    }

    .footer {
        text-align: center;
        font-size: 9px;
        margin-top: 5px;
        color: gray;
    }

    .text-danger {
        color: red;
    }

    .text-warning {
        color: #e67e22;
    }
</style>
<body>
    <div class="header">Change Life Christian Church</div>
    <div class="sub-header"><?= $attendance_month;?></div>
    <hr>
    <?= $tbl_data?>
    <div class="footer">This document has been automatically generated by the system.</div>
</body>
</html>